# Generated by Django 3.2.7 on 2021-10-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('date_of_donation', models.DateField()),
            ],
        ),
    ]
